---
- hosts: pos
  gather_facts: false
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Copiar archivos a los pos
      copy:
        src: /mnt/demo.txt
        dest: /root/demo.txt
        # owner: reg
        # group: users
        # mode: '0644'
        
