---
- hosts: all
  tasks:
    - name: Copiar archivos a los pos
      ansible.builtin.copy:
        src: /mnt/demo.txt
        dest: /root/demo.txt
        owner: reg
        group: users
        mode: '0644'
        
