---
- name: Windows Update
  hosts: all
  gather_facts: false
  tasks:
    - name: Running Windows Update
      win_update:
        category_name: ['Updates']
      register: result

    - debug: var=result
